// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLKzgOPciNbIofjnm62eAR-UYwdwfVNKM',
    appId: '1:1067514893560:web:9ceec573bb73305f48d70d',
    messagingSenderId: '1067514893560',
    projectId: 'modul3a-4d76d',
    authDomain: 'modul3a-4d76d.firebaseapp.com',
    storageBucket: 'modul3a-4d76d.appspot.com',
    measurementId: 'G-M2XJKG4K98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPllNtxEjmqZ9TL_pgq_fjMdjit7Dwxtw',
    appId: '1:1067514893560:android:fc85f34ab360515e48d70d',
    messagingSenderId: '1067514893560',
    projectId: 'modul3a-4d76d',
    storageBucket: 'modul3a-4d76d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYXHsmc3MVVN2Kmixzx2ujQmmzQi_6bw',
    appId: '1:1067514893560:ios:0aff236d2214d25948d70d',
    messagingSenderId: '1067514893560',
    projectId: 'modul3a-4d76d',
    storageBucket: 'modul3a-4d76d.appspot.com',
    iosBundleId: 'com.example.rentalinId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTYXHsmc3MVVN2Kmixzx2ujQmmzQi_6bw',
    appId: '1:1067514893560:ios:0aff236d2214d25948d70d',
    messagingSenderId: '1067514893560',
    projectId: 'modul3a-4d76d',
    storageBucket: 'modul3a-4d76d.appspot.com',
    iosBundleId: 'com.example.rentalinId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLKzgOPciNbIofjnm62eAR-UYwdwfVNKM',
    appId: '1:1067514893560:web:43f8640c99402c8748d70d',
    messagingSenderId: '1067514893560',
    projectId: 'modul3a-4d76d',
    authDomain: 'modul3a-4d76d.firebaseapp.com',
    storageBucket: 'modul3a-4d76d.appspot.com',
    measurementId: 'G-L8PDFEH605',
  );
}
